spring:
  application:
    name: demo-kube
  main:
    banner-mode: "off"
server:
  port: 8082

app:
  name: ${APPLICATION_NAME:no_name}
  info: ${APPLICATION_INFO:no_info}
  test_sc: ${INFO_SEC:no_info_Sec}