apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  labels:
    app: app-demo
spec:
  selector:
    matchLabels:
      app: app-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image: gianmilani/kube-demo:v3
        env:
          - name: APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: app-demo-env
                key: APPLICATION_NAME
          - name: APPLICATION_INFO
            valueFrom:
              configMapKeyRef:
                name: app-demo-env
                key: APPLICATION_INFO