spring.config.import=optional:file:.env[.properties]
test.user.name=${TEST_USER_NAME}
test.user.age=${TEST_USER_AGE}
test.list=${LIST_FRUITS}
test.secret=${MY_SECRET}
test.server=${ANY_SERVER}
test.port=${ANY_PORT}