apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
  labels:
    app: spring-api
spec:
  selector:
    matchLabels:
      app: spring-api-container
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-api-container
    spec:
      containers:
        - name: spring-api-container
          image: "gianmilani/app-spring-test:v5.3"
          livenessProbe:
            httpGet:
              path: /health-prob
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 50
          readinessProbe:
            httpGet:
              path: /health-prob
              port: 8080
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 20
          env:
          - name: TEST_USER_NAME
            value: "Joseph Climber"
          - name : TEST_USER_AGE
            valueFrom:
              configMapKeyRef:
                name: api-spring-env
                key: TEST_USER_AGE
          envFrom:
            - configMapRef:
                name: configmap-list-fruit
            - secretRef:
                name: app-spring-secret
          volumeMounts:
            - mountPath: "/usr/app/config"
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: configmap-server-info
            items:
            - key: info
              path: ".env"  