apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
  labels:
    app: spring-api
spec:
  selector:
    matchLabels:
      app: spring-api-container
  replicas: 5
  template:
    metadata:
      labels:
        app: spring-api-container
    spec:
      containers:
      - name: spring-api-container
        image: "gianmilani/app-spring-test:v2"
